name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ "main", "gh-pages" ] # Trigger on pushes to EITHER branch

permissions:
  contents: write # Needed for the build job to push to gh-pages
  pages: write
  id-token: write

jobs:
  # This job builds the app and pushes it to the gh-pages branch
  build:
    if: github.ref == 'refs/heads/main' # Only run this job for pushes to main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Prepare for Production Build
        run: cp composeApp/src/wasmJsMain/resources/index.prod.html composeApp/src/wasmJsMain/resources/index.html

      - name: Build Web App
        run: ./gradlew clean :composeApp:wasmJsBrowserDistribution

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./composeApp/build/dist/wasmJs/productionExecutable
          publish_branch: gh-pages # Explicitly push to gh-pages