name: Deploy Web to GitHub Pages

on:
  push:
    branches: [ "main" ]

# Grant permissions for deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Job 1: Build the web app and upload it as an artifact
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Web App
        run: ./gradlew clean :composeApp:wasmJsBrowserDistribution

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./composeApp/build/dist/wasmJs/productionExecutable/

  # Job 2: Deploy the artifact to GitHub Pages
  deploy:
    needs: build # This job runs only after the 'build' job succeeds
    runs-on: ubuntu-latest

    # Add this environment block
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4