name: Deploy Web to GitHub Pages

on:
  push:
    branches: [ "main" ] # Trigger the workflow on push to the main branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use a standard Linux runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Step 1: Get your code from the repo

      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Step 2: Set up Java for Gradle
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Web App
        run: ./gradlew clean :composeApp:wasmJsBrowserDistribution # Step 3: Build the static web files

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Step 4: Deploy the built files
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./composeApp/build/dist/js/productionExecutable # Directory with the web files
          keep_files: false